### ISSUE TITLE
I'm getting this error,can u please solve it asap

### ISSUE THREAD

**Issue by satwik-ops** [farizkhan0687/ROSPL_project#15]
![WhatsApp Image 2022-10-16 at 5 28 41 PM](https://user-images.githubusercontent.com/83078136/196034220-283acaf6-b718-4a8b-b8b4-91bd0fdd455e.jpeg)

**Comment by farizkhan0687** [comment]
name variable should contain two underscores before and after, like this: __name__
And the name of the environment which is main should contain two underscores before and after, like this:  "__main__"
